name: desktop_webview_auth_example
description: Demonstrates how to use the desktop_webview_auth plugin.

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  googleapis: ^11.2.0
  googleapis_auth: ^1.1.0
  flutter:
    sdk: flutter

  desktop_webview_auth:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
